ListProject/app1/urls.py
from .import views
from django.urls import path
app_name='app1'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('classhome',views.MovieListView.as_view(),name='classhome'),
    path('classdetail/<int:pk>/',views.MovieDetailView.as_view(),name='classdetail'),
    path('classupdate/<int:pk>/',views.MovieUpdateView.as_view(),name='classupdate'),
    path('classdelete/<int:pk>/',views.MovieDeleteView.as_view(),name='classdelete'),
    path('mailview',views.emailsend,name='emailsend')
]

ListProject/project1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ListProject/app1/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=200)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='pics')
    def __str__(self):
        return self.name

ListProject/app1/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','image']

ListProject/app1/views.py
import kwargs as kwargs
from django.shortcuts import render, redirect
from django.http import HttpResponse
# Create your views here.
from django.urls import reverse_lazy

from .models import Movie
from .forms import MovieForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView
from django.core.mail import send_mail



def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})

def add(request):
    if request.method == 'POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        image=request.FILES['image']
        movie=Movie(name=name,desc=desc,year=year,image=image)
        movie.save();
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
     if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
     return render(request,'delete.html')

class MovieListView(ListView):
    model = Movie
    template_name = 'index.html'
    context_object_name = 'movie_list'

class MovieDetailView(DetailView):
    model=Movie
    template_name = 'detail.html'
    context_object_name = 'movie'

class MovieUpdateView(UpdateView):
    model = Movie
    template_name = 'update.html'
    context_object_name = 'movie'
    fields =('name','desc','year','image')

    def get_success_url(self):
        return reverse_lazy('app1:classdetail',kwargs={'pk':self.object.id})
class MovieDeleteView(DeleteView):
    model = Movie
    template_name = 'delete.html'
    success_url = reverse_lazy('app1:classhome')

def emailsend(request):
    send_mail('Testing email','Testing message for program','fasinifasil@gmail.com',['mahase8883@kuvasin.com','bismina1995@gmail.com'],fail_silently=False,)
    return HttpResponse('email send')

ListProject/templates/add.html
{% extends 'base.html' %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    Name:<input type="text" name="name" placeholder="name"><br>
    Description:<input type="textarea" name="desc" placeholder="description"><br>
    Year:<input type="year" name="year" placeholder="Year"><br>
    Image:<input type="file" name="image"><br>
    <input type="submit">

</form>

{% endblock %}

ListProject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">

</head>

<body>
<!-- Image and text -->
<nav class="navbar navbar- bg-dark">
  <a class="navbar-brand" href="#">
<!--    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">-->
    Bootstrap
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

ListProject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <h3> Are you sure you want to delete?</h3>
    <input type="submit">

</form>
{% endblock %}

ListProject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}" height="300" width="300">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h5>{{movie.desc}}</h5>>
            <h4>{{movie.year}}</h4>
            <a class="btn btn-primary" href="{% url 'app1:update' movie.id %}">Update</a>
            <a class="btn btn-primary" href="{% url 'app1:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

ListProject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">confirm</button>
</form>
{% endblock %}

ListProject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="card-deck mt-4" style="width:400px">
        <div class="col-md-3">
            <div class="card" style="width:18rem;">
      <img src="{{i.image.url}}" class="card-img-top" alt="Card image cap" height='250px'>
      <div class="card-body">
          <h5 class="card-title">{{i.name}}</h5>
          <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'app1:detail' i.id %}" class="btn btn-primary">Go</a>
  </div>
        </div>
</div>
    </div>

        {% endfor %}

</div>
</div>
{% endblock %}

ListProject/templates/update.html
{% extends 'base.html' %}
{% block body %}
    <div class="card">
        <div class="class-header">
            <div class="'card-title">
                Update Movie
            </div>
            <div class="car-body">
            <form method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Confirm</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}